# -*- coding: utf-8 -*-
"""repo2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EbAusGhrGr9EWVepn9CWOUovG7IJw8Af
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

from google.colab import files
uploaded = files.upload()

df = pd.read_excel("HARGA RUMAH JAKSEL.xlsx")

print("📋 5 Data Pertama:")
display(df.head())

print("\n📊 Info Dataset:")
print(df.info())

if 'HARGA' not in df.columns:
    df.columns = df.iloc[0]  # set baris pertama jadi header
    df = df[1:]              # hapus baris pertama dari data
    df.reset_index(drop=True, inplace=True)

# Hapus spasi di nama kolom
df.columns = df.columns.str.strip()

print("📋 Kolom yang terbaca:")
print(df.columns.tolist())

display(df.head())

df.columns = df.columns.str.strip()
df['HARGA'] = df['HARGA'].replace({',': ''}, regex=True).astype(float)
df['GRS'] = df['GRS'].replace({'ADA': 1, 'TIDAK ADA': 0})
df = df.dropna()

print("\n✅ Data setelah dibersihkan:")
display(df.head())
plt.figure(figsize=(8,5))
sns.histplot(df['HARGA'], bins=20, kde=True)
plt.title("Distribusi Harga Rumah")
plt.xlabel("Harga Rumah (Rp)")
plt.ylabel("Frekuensi")
plt.show()


# Korelasi antar variabel numerik
plt.figure(figsize=(7,5))
sns.heatmap(df.drop(columns=['KOTA']).corr(numeric_only=True), annot=True, cmap="Blues")
plt.title("Korelasi Antar Variabel")
plt.show()

fig, axes = plt.subplots(1, 2, figsize=(12,5))
sns.scatterplot(x='LT', y='HARGA', data=df, ax=axes[0])
axes[0].set_title('Luas Tanah vs Harga Rumah')
sns.scatterplot(x='LB', y='HARGA', data=df, ax=axes[1])
axes[1].set_title('Luas Bangunan vs Harga Rumah')
plt.show()

X = df[['LT', 'LB', 'JKT', 'JKM', 'GRS']]
y = df['HARGA']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

model = LinearRegression()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

r2 = r2_score(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)

print("📈 Evaluasi Model:")
print(f"R² Score : {r2:.4f}")
print(f"MSE       : {mse:.2f}")
print(f"RMSE      : {rmse:.2f}")

plt.figure(figsize=(7,5))
plt.scatter(y_test, y_pred, color='blue')
plt.xlabel("Harga Aktual")
plt.ylabel("Harga Prediksi")
plt.title("Prediksi vs Aktual Harga Rumah")
plt.plot([y.min(), y.max()], [y.min(), y.max()], color='red', linestyle='--')
plt.show()


coef_df = pd.DataFrame({'Faktor': X.columns, 'Koefisien': model.coef_})
print("\n📊 Pengaruh Masing-masing Faktor:")
display(coef_df)

print("Kesimpulan:")
print("- Semakin besar luas tanah dan luas bangunan, semakin tinggi harga rumah.")
print("- Rumah dengan garasi cenderung memiliki harga lebih tinggi.")
print("- Nilai R² menunjukkan seberapa baik model menjelaskan variasi harga rumah.")